# Generated by Django 3.2 on 2022-02-25 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='comment',
        ),
    ]
